import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Portofolio | Frédéric OUDENOT",
  description: " Portofolio Frédéric OUDENOT generated by Nextjs",
};



export default function RootLayout(
  {
  children,
}: Readonly<{
  children: React.ReactNode;
}>
) {
  return (
    <>
      <head>
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/devicon.min.css"
        />
      </head>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </>
  );
}
